---
############################################################
#                   Data information                       #
############################################################

ref: ref.yaml
assembly: mm10 #hg38 or mm10

cancer_type: AUTO #short name of cancer type
metasheet: metasheet.txt
designs: [Condition] #the column from metasheet which is used to do comparsion

############################################################
#                     Data Processing                      #
############################################################

### star 
#Possible values are [ff-firststrand, ff-secondstrand, ff-unstranded, fr-firststrand, fr-secondstrand, fr-unstranded (default), transfrags]
library_type: 'fr-firststrand'
stranded: true
threads: 8

### rseqc parameters
rseqc_ref: house_keeping  #rseqc ref model

############################################################
#             Differential Gene Expression                 #
############################################################


### batch_removal and PCA analysis
#If you don't need to do batch removal, just setting [no] 
batch_covariates: [no]

neoantigen_callers: "NetMHC"
neoantigen_epitope_lengths: "8,9,10,11"

### deseq2
batch: [no] #[Clinical Phenotype] or [no], Clinical phenotype could be the column from metasheet which accounts for batch effect
comparison: between ##between or loop. between: compare any two phenotypes in a given condition column;loop: compare one phenotype and all the others 

############################################################
#                       level3                             #
############################################################

### microbiota
centrifuge: true  #run centrifuge or pathseq

### Trust4
trust4_clinical_phenotype: [Condition]

### arcasHLA
##specifying group imformation annotated in HLA oncoplot
hla_annot_group: [Responder, Gender]

############################################################
#                     list samples                         #
############################################################
samples:
  SRR8281228:
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281228_1.fastq.gz
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281228_2.fastq.gz
  SRR8281222:
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281222_1.fastq.gz
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281222_2.fastq.gz
  SRR8281224:
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281224_1.fastq.gz
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281224_2.fastq.gz
  SRR8281225:
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281225_1.fastq.gz
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281225_2.fastq.gz
  SRR8281218:
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281218_1.fastq.gz
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281218_2.fastq.gz
  SRR8281219:
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281219_1.fastq.gz
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281219_2.fastq.gz
  SRR8281220:
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281220_1.fastq.gz
    - /liulab/yang/Immunotherapy/toDIGEST/rawRNASeq/fastq/Zhao2019_PD1_Glioblastoma_RNASeq/SRR8281220_2.fastq.gz

###########################################################
#                      run settings                       #
###########################################################
runs:
  run1:
    - SRR8281228
  run3:
    - SRR8281222
  run4:
    - SRR8281224
  run5:
    - SRR8281225
  run6:
    - SRR8281218
  run7:
    - SRR8281219
  run8:
    - SRR8281220

