---
metasheet: metasheet.csv
ref: ref.yaml
assembly: hg38
cancer_type: GBM


#########User defined parameters needed to run the modules################
#------- preprocess  module--------#
rseqc_ref: house_keeping  #rseqc ref model
mate: [1,2] #paired-end([1,2]) or single-end([0])


###deseq2
batch: syn_batch #False or batch colname in metasheet
design: Group #condition to do comparsion
Treatment: R
Control: NR


####
pre-treated : True
#--------mutation------------#
fusion_clinical_phenotypes: [Responder]

#--------neoantigen module----------#
hla_annot_group: [Responder, Gender]
neoantigen_callers: "NetMHC"
neoantigen_epitope_lengths: "8,9,10,11"

#------Multiqc report-----------#
#Re-order the sample by phenotype:
sam_ord: [Responder]

############################################################
#                     list samples                         #
############################################################

samples:
  SRR8281218.01:
    - /mnt/RIMA/data/SRR8281218_1.fastq.gz
    - /mnt/RIMA/data/SRR8281218_2.fastq.gz
  SRR8281219:
    - /mnt/RIMA/data/SRR8281219_1.fastq.gz
    - /mnt/RIMA/data/SRR8281219_2.fastq.gz
  SRR8281226:
    - /mnt/RIMA/data/SRR8281226_1.fastq.gz
    - /mnt/RIMA/data/SRR8281226_2.fastq.gz
  SRR8281236:
    - /mnt/RIMA/data/SRR8281236_1.fastq.gz
    - /mnt/RIMA/data/SRR8281236_2.fastq.gz
  SRR8281230:
    - /mnt/RIMA/data/SRR8281230_1.fastq.gz
    - /mnt/RIMA/data/SRR8281230_2.fastq.gz
  SRR8281233:
    - /mnt/RIMA/data/SRR8281233_1.fastq.gz
    - /mnt/RIMA/data/SRR8281233_2.fastq.gz
  SRR8281244:
    - /mnt/RIMA/data/SRR8281244_1.fastq.gz
    - /mnt/RIMA/data/SRR8281244_2.fastq.gz
  SRR8281245:
    - /mnt/RIMA/data/SRR8281245_1.fastq.gz
    - /mnt/RIMA/data/SRR8281245_2.fastq.gz
  SRR8281243:
    - /mnt/RIMA/data/SRR8281243_1.fastq.gz
    - /mnt/RIMA/data/SRR8281243_2.fastq.gz
  SRR8281251:
    - /mnt/RIMA/data/SRR8281251_1.fastq.gz
    - /mnt/RIMA/data/SRR8281251_2.fastq.gz
  SRR8281238:
    - /mnt/RIMA/data/SRR8281238_1.fastq.gz
    - /mnt/RIMA/data/SRR8281238_2.fastq.gz
  SRR8281250:
    - /mnt/RIMA/data/SRR8281250_1.fastq.gz
    - /mnt/RIMA/data/SRR8281250_2.fastq.gz

############################################################
#                    Neoantigen testing                    #
############################################################
VCF:  #vcf files for tumor samples
  SRR8281228:
    - /mnt/zhao_trial/test_lin/analysis/vcf/SRR8281228_tnscope.filter.neoantigen.vep.vcf
  SRR8281231:
    - /mnt/zhao_trial/test_lin/analysis/vcf/SRR8281231_tnscope.filter.neoantigen.vep.vcf
  SRR8281222:
    - /mnt/zhao_trial/test_lin/analysis/vcf/SRR8281222_tnscope.filter.neoantigen.vep.vcf
  SRR8281224:
    - /mnt/zhao_trial/test_lin/analysis/vcf/SRR8281224_tnscope.filter.neoantigen.vep.vcf
  SRR8281225:
    - /mnt/zhao_trial/test_lin/analysis/vcf/SRR8281225_tnscope.filter.neoantigen.vep.vcf

