---
metasheet: metasheet.csv
ref: ref.yaml
assembly: hg38
cancer_type: GBM


#########User defined parameters needed to run the modules################
#------- preprocess  module--------#
rseqc_ref: house_keeping  #rseqc ref model
mate: [1,2] #paired-end([1,2]) or single-end([0])

#----- differential expression module------#
##batch_removal and pca analysis
batch_covariates: [TumorLocation]

###deseq2
batch: no #no or batch colname in metasheet
designs: [Responder] #condition to do comparsion
comparison: between ##between or loop. between: compare any two phenotypes in a given condition column;loop: compare one phenotype and all the others

##ssgsea
ssgsea_comparisons: [Responder]
ssgsea_top_n_terms: 50

#---------immune infiltration module------#
immune_infiltration_clinical_phenotype: Responder
immunerepertoire_clinical_phenotype: [Responder]

#---------immune response module---------#
tide_cancer: Other
#tide_compare_tcga_cancer: LUAD
control: true
msi_clinical_phenotypes: [Responder]

#--------mutation------------#
fusion_clinical_phenotypes: [Responder]

#--------neoantigen module----------#
hla_annot_group: [Responder, Gender]
neoantigen_callers: "NetMHC"
neoantigen_epitope_lengths: "8,9,10,11"

#------Multiqc report-----------#
#Re-order the sample by phenotype:
sam_ord: [Responder]

############################################################
#                     list samples                         #
############################################################

samples:
  SRR8281218:
    - /mnt/zhao_trial/data/SRR8281218_1.fastq.gz
    - /mnt/zhao_trial/data/SRR8281218_2.fastq.gz
  SRR8281219:
    - /mnt/zhao_trial/data/SRR8281219_1.fastq.gz
    - /mnt/zhao_trial/data/SRR8281219_2.fastq.gz
  SRR8281226:
    - /mnt/zhao_trial/data/SRR8281226_1.fastq.gz
    - /mnt/zhao_trial/data/SRR8281226_2.fastq.gz
  SRR8281236:
    - /mnt/zhao_trial/data/SRR8281236_1.fastq.gz
    - /mnt/zhao_trial/data/SRR8281236_2.fastq.gz
  SRR8281230:
    - /mnt/zhao_trial/data/SRR8281230_1.fastq.gz
    - /mnt/zhao_trial/data/SRR8281230_2.fastq.gz
  SRR8281233:
    - /mnt/zhao_trial/data/SRR8281233_1.fastq.gz
    - /mnt/zhao_trial/data/SRR8281233_2.fastq.gz
  SRR8281244:
    - /mnt/zhao_trial/data/SRR8281244_1.fastq.gz
    - /mnt/zhao_trial/data/SRR8281244_2.fastq.gz
  SRR8281245:
    - /mnt/zhao_trial/data/SRR8281245_1.fastq.gz
    - /mnt/zhao_trial/data/SRR8281245_2.fastq.gz
  SRR8281243:
    - /mnt/zhao_trial/data/SRR8281243_1.fastq.gz
    - /mnt/zhao_trial/data/SRR8281243_2.fastq.gz
  SRR8281251:
    - /mnt/zhao_trial/data/SRR8281251_1.fastq.gz
    - /mnt/zhao_trial/data/SRR8281251_2.fastq.gz
  SRR8281238:
    - /mnt/zhao_trial/data/SRR8281238_1.fastq.gz
    - /mnt/zhao_trial/data/SRR8281238_2.fastq.gz
  SRR8281250:
    - /mnt/zhao_trial/data/SRR8281250_1.fastq.gz
    - /mnt/zhao_trial/data/SRR8281250_2.fastq.gz


############################################################
#                       run settings                       #
############################################################
runs:
  run1:
    - SRR8281218
  run2:
    - SRR8281219
  run3:
    - SRR8281226
  run4:
    - SRR8281238
  run5:
    - SRR8281236
  run6:
    - SRR8281230
  run7:
    - SRR8281233
  run8:
    - SRR8281244
  run9:
    - SRR8281245
  run10:
    - SRR8281243
  run11:
    - SRR8281251
  run12:
    - SRR8281250

############################################################
#                    Neoantigen testing                    #
############################################################
VCF:  #vcf files for tumor samples
  SRR8281228:
    - /mnt/zhao_trial/test_lin/analysis/vcf/SRR8281228_tnscope.filter.neoantigen.vep.vcf
  SRR8281231:
    - /mnt/zhao_trial/test_lin/analysis/vcf/SRR8281231_tnscope.filter.neoantigen.vep.vcf
  SRR8281222:
    - /mnt/zhao_trial/test_lin/analysis/vcf/SRR8281222_tnscope.filter.neoantigen.vep.vcf
  SRR8281224:
    - /mnt/zhao_trial/test_lin/analysis/vcf/SRR8281224_tnscope.filter.neoantigen.vep.vcf
  SRR8281225:
    - /mnt/zhao_trial/test_lin/analysis/vcf/SRR8281225_tnscope.filter.neoantigen.vep.vcf

