#########Fixed and user-defined parameters################
metasheet: metasheet.csv  # Meta info 
ref: ref.yaml             # Reference config 
assembly: mm10
cancer_type: GBM          #TCGA cancer type abbreviations
rseqc_ref: house_keeping  #Option: 'house_keeping' or 'false'. 
                          #By default, a subset of housekeeping genes is used by RSeQC to assess alignment quality.  
                          #This reduces the amount of time needed to run RSeQC.  
mate: [1,2]               #paired-end fastq format, we recommend naming paired-end reads with _1.fq.gz and _2.fq.gz


#########Cohort level analysis parameters################
design: GSE_ID             # Condition on which to do comparsion (as set up in metasheet.csv)
Treatment: GSE149815              # Treatment use in DESeq2, corresponding to positive log fold change
Control: GSE98672               # Control use in DESeq2, corresponding to negative log fold change
batch: syn_batch          # Options: 'false' or a column name from the metasheet.csv.  
                          # If set to a column name in the metasheet.csv, the column name will be used for batch effect analysis                                (limma).  
                          # It will also be used as a covariate for differential analysis (DESeq2) to account for batch effect.  

############################################################
#                     list samples                         #
############################################################
samples:
  SRX8245648:
    - /liulab/nofal/syng_raw_data_new/GSE149815/SRX8245648/SRR11684859/SRR11684859_2.fastq.gz
    - /liulab/nofal/syng_raw_data_new/GSE149815/SRX8245648/SRR11684859/SRR11684859_1.fastq.gz
  SRX8245632:
    - /liulab/nofal/syng_raw_data_new/GSE149815/SRX8245632/SRR11684843/SRR11684843_2.fastq.gz
    - /liulab/nofal/syng_raw_data_new/GSE149815/SRX8245632/SRR11684843/SRR11684843_1.fastq.gz
  SRX8245638:
    - /liulab/nofal/syng_raw_data_new/GSE149815/SRX8245638/SRR11684849/SRR11684849_1.fastq.gz
    - /liulab/nofal/syng_raw_data_new/GSE149815/SRX8245638/SRR11684849/SRR11684849_2.fastq.gz
  SRX8245621:
    - /liulab/nofal/syng_raw_data_new/GSE149815/SRX8245621/SRR11684832/SRR11684832_2.fastq.gz
    - /liulab/nofal/syng_raw_data_new/GSE149815/SRX8245621/SRR11684832/SRR11684832_1.fastq.gz
  SRX8245619:
    - /liulab/nofal/syng_raw_data_new/GSE149815/SRX8245619/SRR11684830/SRR11684830_1.fastq.gz
    - /liulab/nofal/syng_raw_data_new/GSE149815/SRX8245619/SRR11684830/SRR11684830_2.fastq.gz
  SRX2790943:
    - /liulab/nofal/syng_raw_data_new/GSE98672/SRX2790943/SRR5517574/SRR5517574_2.fastq.gz
    - /liulab/nofal/syng_raw_data_new/GSE98672/SRX2790943/SRR5517574/SRR5517574_1.fastq.gz
